Allow updating render test references from CI (#106)
* Use correct output directory for render tests
* Add job for render-test report
* Download artifacts from failed workflow runs
* Report render test failures to job summary
* Add link to summary
* Update references and commit to the repo

diff --git a/.github/workflows/Build-and-Test.yml b/.github/workflows/Build-and-Test.yml
--- a/.github/workflows/Build-and-Test.yml
+++ b/.github/workflows/Build-and-Test.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches: [ main ]
   pull_request:
-    branches: [ main ]
   workflow_dispatch:
     inputs:
       profile-cmake:
@@ -16,6 +15,11 @@ on:
         description: 'Enable code coverage'
         required: true
         default: true
+        type: boolean
+      update-references:
+        description: 'Update render test references'
+        required: true
+        default: false
         type: boolean
 
 env:
@@ -68,6 +72,11 @@ jobs:
     env:
       job_name: ${{startsWith(matrix.runner, 'windows') && 'Windows' || 'Linux'}}-${{matrix.buildtype}}-${{matrix.preset}}${{matrix.name-suffix}}
       CMAKE_BUILD_TYPE: ${{matrix.buildtype}}
+      RT_OUTPUT_DIR: build/${{matrix.preset}}/tests/RenderTest/RenderTestOutput
+
+    outputs:
+      rendertest-failures: ${{steps.rendertest.outputs.failure == 'true'}}
+      rendertest-successes: ${{steps.rendertest.outputs.success == 'true'}}
 
     steps:
     - name: Checkout
@@ -146,7 +155,18 @@ jobs:
       uses: actions/upload-artifact@v3
       with:
         name: RenderTestOutput-${{env.job_name}}
-        path: RenderTestOutput
+        path: ${{env.RT_OUTPUT_DIR}}
+
+    - name: Record render test outcome
+      id: rendertest
+      if: always()
+      shell: bash
+      run: |
+        if [ -d "$RT_OUTPUT_DIR" ]; then
+          echo "failure=true" >> "$GITHUB_OUTPUT"
+        else
+          echo "success=true" >> "$GITHUB_OUTPUT"
+        fi
 
     - name: Save test log
       if: failure() && steps.test.outcome == 'failure'
@@ -171,11 +191,69 @@ jobs:
         name: CoverageReport-${{env.job_name}}
         path: build/${{matrix.preset}}/coverage/output
 
+  render-test-report:
+    name: Render-Test-Report
+    runs-on: ubuntu-latest
+    needs: [unified]
+    if: always() && needs.unified.outputs.rendertest-failures
+    env:
+      GH_TOKEN: ${{github.token}}
+      ANY_PASSED: "${{needs.unified.outputs.rendertest-successes}}"
+
+    steps:
+    - uses: actions/download-artifact@v3
+      with:
+        path: artifacts
+
+    - name: Generate summary
+      run: |
+        URL="https://markridgewell.github.io/TeideStats/rendertest.html?run_id=${{github.run_id}}"
+        echo "Render tests failed. [Click for details]($URL)" >> $GITHUB_STEP_SUMMARY
+
+    - name: Display structure of downloaded files
+      run: ls -R
+      working-directory: artifacts
+
+    - name: Checkout
+      if: inputs.update-references
+      uses: actions/checkout@v3
+      with:
+        lfs: true
+        submodules: false
+        path: repo
+
+    - name: Update references
+      if: inputs.update-references
+      working-directory: repo
+      env:
+        REFERENCES_DIR: tests/RenderTest/references
+      run: |
+        if $ANY_PASSED; then
+          echo "Not all render tests failed, cannot update references"
+          exit 1
+        else
+          python tools/update_references.py ../artifacts $REFERENCES_DIR
+        fi
+
+        echo Staging changes...
+        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+        git add $REFERENCES_DIR
+        echo
+
+        echo Status:
+        git status
+        echo
+
+        echo Pushing changes...
+        git commit -m "Update render test references"
+        git push
+
   time-report:
     name: Time-Report
     runs-on: ubuntu-latest
     needs: [unified]
-    if: ${{ github.event_name == 'push' }}
+    if: github.event_name == 'push'
     env:
       GH_TOKEN: ${{github.token}}
 
